export const CALENDAR_2026 = [
  { round: 1, code: "AUS", name: "Australian Grand Prix", date: "06-08 Mar" },
  { round: 2, code: "CHN", name: "Chinese Grand Prix", date: "13-15 Mar" },
  { round: 3, code: "JPN", name: "Japanese Grand Prix", date: "27-29 Mar" },
  { round: 4, code: "BAH", name: "Bahrain Grand Prix", date: "10-12 Apr" },
  { round: 5, code: "SAU", name: "Saudi Arabian Grand Prix", date: "17-19 Apr" },
  { round: 6, code: "MIA", name: "Miami Grand Prix", date: "01-03 May" },
  { round: 7, code: "CAN", name: "Canadian Grand Prix", date: "22-24 May" },
  { round: 8, code: "MON", name: "Monaco Grand Prix", date: "05-07 Jun" },
  { round: 9, code: "CAT", name: "Barcelona-Catalunya Grand Prix", date: "12-14 Jun" },
  { round: 10, code: "AUT", name: "Austrian Grand Prix", date: "26-28 Jun" },
  { round: 11, code: "GBR", name: "British Grand Prix", date: "03-05 Jul" },
  { round: 12, code: "BEL", name: "Belgian Grand Prix", date: "17-19 Jul" },
  { round: 13, code: "HUN", name: "Hungarian Grand Prix", date: "24-26 Jul" },
  { round: 14, code: "NED", name: "Dutch Grand Prix", date: "21-23 Aug" },
  { round: 15, code: "ITA", name: "Italian Grand Prix", date: "04-06 Sep" },
  { round: 16, code: "ESP", name: "Spanish Grand Prix", date: "11-13 Sep" },
  { round: 17, code: "AZE", name: "Azerbaijan Grand Prix", date: "24-26 Sep" },
  { round: 18, code: "SIN", name: "Singapore Grand Prix", date: "09-11 Oct" },
  { round: 19, code: "USA", name: "United States Grand Prix", date: "23-25 Oct" },
  { round: 20, code: "MEX", name: "Mexico City Grand Prix", date: "30 Oct-01 Nov" },
  { round: 21, code: "BRA", name: "São Paulo Grand Prix", date: "06-08 Nov" },
  { round: 22, code: "LVG", name: "Las Vegas Grand Prix", date: "19-21 Nov" },
  { round: 23, code: "QAT", name: "Qatar Grand Prix", date: "27-29 Nov" },
  { round: 24, code: "ABU", name: "Abu Dhabi Grand Prix", date: "04-06 Dec" },
]